-- =====================================================================
-- V10 数字孪生生产化配置
--
-- 场景资产从“前端写死一个山体”提升为“每个项目一份可版本化配置”。
-- 资产本身由前端同源静态目录或对象存储提供，数据库只保存类型、坐标与校验元数据。
-- =====================================================================

CREATE TABLE digital_twin_scene (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    project_id             BIGINT NOT NULL,
    enabled                BOOLEAN NOT NULL DEFAULT TRUE,
    asset_type             VARCHAR(16) NOT NULL,       -- GLB / 3D_TILES
    coordinate_mode        VARCHAR(16) NOT NULL,       -- ENU / EMBEDDED
    asset_url              VARCHAR(512) NOT NULL,
    asset_version          VARCHAR(64) NOT NULL,
    asset_sha256           VARCHAR(64),
    anchor_longitude       NUMERIC(12, 7),
    anchor_latitude        NUMERIC(12, 7),
    anchor_height          NUMERIC(10, 3),
    heading_degrees        NUMERIC(9, 4) NOT NULL DEFAULT 0,
    pitch_degrees          NUMERIC(9, 4) NOT NULL DEFAULT 0,
    roll_degrees           NUMERIC(9, 4) NOT NULL DEFAULT 0,
    model_scale            NUMERIC(12, 6) NOT NULL DEFAULT 1,
    camera_heading_degrees NUMERIC(9, 4) NOT NULL DEFAULT 0,
    camera_pitch_degrees   NUMERIC(9, 4) NOT NULL DEFAULT -35,
    camera_range           NUMERIC(12, 3) NOT NULL DEFAULT 1000,
    maximum_screen_error   NUMERIC(8, 3) NOT NULL DEFAULT 16,
    maximum_memory_mb      INT NOT NULL DEFAULT 512,
    max_heat_points        INT NOT NULL DEFAULT 200,
    label_distance         NUMERIC(12, 3) NOT NULL DEFAULT 2000,
    deleted                INT NOT NULL DEFAULT 0,
    created_at             TIMESTAMP,
    updated_at             TIMESTAMP,
    CONSTRAINT uk_digital_twin_scene_project UNIQUE (project_id)
);

-- 雷达在数字孪生场景中的姿态与覆盖参数。经纬度沿用 device 原字段；这里补齐高程和姿态。
ALTER TABLE device ADD COLUMN altitude NUMERIC(10, 3);
ALTER TABLE device ADD COLUMN heading_degrees NUMERIC(9, 4);
ALTER TABLE device ADD COLUMN pitch_degrees NUMERIC(9, 4);
ALTER TABLE device ADD COLUMN detection_range_m NUMERIC(12, 3);
ALTER TABLE device ADD COLUMN half_angle_degrees NUMERIC(9, 4);

INSERT INTO digital_twin_scene (
    id, project_id, enabled, asset_type, coordinate_mode, asset_url, asset_version, asset_sha256,
    anchor_longitude, anchor_latitude, anchor_height,
    heading_degrees, pitch_degrees, roll_degrees, model_scale,
    camera_heading_degrees, camera_pitch_degrees, camera_range,
    maximum_screen_error, maximum_memory_mb, max_heat_points, label_distance,
    created_at, updated_at
) VALUES (
    1, 1, TRUE, 'GLB', 'ENU', '/models/mountain-demo/mountain-demo.glb', 'mountain-demo-1.0.0',
    '40aaf4e548a78ce67b048f1557d1a050e1aae2a392b764c62a2e3188339bf5b3',
    113.0508000, 23.7208000, 2.000,
    0.0, 0.0, 0.0, 1.0,
    327.0, -36.0, 430.0,
    16.0, 512, 200, 2000.0,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

UPDATE device
SET altitude = 20.080,
    heading_degrees = 38.0,
    pitch_degrees = 0.0,
    detection_range_m = 265.0,
    half_angle_degrees = 25.0,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1;

