-- =====================================================================
-- V1 初始 schema（A 统一维护）
-- 说明：使用标准 SQL（H2 与 PostgreSQL 通用）；主键 BIGINT 自增；
--       软删除字段 deleted（1=删除 0=正常）由 MyBatis-Plus 逻辑删除接管。
--       约定：identity 一律 (START WITH 1000)——种子数据显式占用 1~N，
--       应用自增从 1000 起，两者互不冲突（避免“显式插 id 后序列仍在 1”撞主键）。
-- =====================================================================

-- ---------- 组织 / 用户 ----------
CREATE TABLE organization (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    name       VARCHAR(128) NOT NULL,
    code       VARCHAR(64),
    contact    VARCHAR(64),
    phone      VARCHAR(32),
    deleted    INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE sys_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    username        VARCHAR(64)  NOT NULL,
    password        VARCHAR(128) NOT NULL,
    display_name    VARCHAR(64),
    role            VARCHAR(32)  NOT NULL,
    organization_id BIGINT,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    deleted         INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT uk_sys_user_username UNIQUE (username)
);

-- ---------- 项目 -> 场景 -> 对象 -> 测点 -> 测项 ----------
CREATE TABLE project (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    organization_id BIGINT,
    name            VARCHAR(128) NOT NULL,
    code            VARCHAR(64),
    location        VARCHAR(255),
    description     VARCHAR(512),
    deleted         INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP
);

CREATE TABLE scene (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    project_id  BIGINT NOT NULL,
    name        VARCHAR(128) NOT NULL,
    type        VARCHAR(32),
    description VARCHAR(512),
    deleted     INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);

CREATE TABLE monitor_object (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    scene_id    BIGINT NOT NULL,
    name        VARCHAR(128) NOT NULL,
    type        VARCHAR(32),
    description VARCHAR(512),
    deleted     INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);

CREATE TABLE monitor_point (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    object_id   BIGINT NOT NULL,
    code        VARCHAR(64) NOT NULL,
    name        VARCHAR(128) NOT NULL,
    type        VARCHAR(32),
    longitude   NUMERIC(12, 7),
    latitude    NUMERIC(12, 7),
    altitude    NUMERIC(10, 3),
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    deleted     INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT uk_monitor_point_code UNIQUE (code)
);

CREATE TABLE metric (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    point_id   BIGINT NOT NULL,
    code       VARCHAR(16)  NOT NULL,
    name       VARCHAR(64)  NOT NULL,
    unit       VARCHAR(16),
    sort_order INT NOT NULL DEFAULT 0,
    deleted    INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- ---------- 设备 ----------
CREATE TABLE device (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    code             VARCHAR(64) NOT NULL,
    name             VARCHAR(128) NOT NULL,
    type             VARCHAR(32),
    serial_no        VARCHAR(64),
    longitude        NUMERIC(12, 7),
    latitude         NUMERIC(12, 7),
    status           VARCHAR(32),
    battery          NUMERIC(6, 2),
    last_report_time TIMESTAMP,
    deleted          INT NOT NULL DEFAULT 0,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP,
    CONSTRAINT uk_device_code UNIQUE (code)
);

CREATE TABLE device_point (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    device_id BIGINT NOT NULL,
    point_id  BIGINT NOT NULL,
    CONSTRAINT uk_device_point UNIQUE (device_id, point_id)
);

CREATE TABLE maintenance_record (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    device_id   BIGINT NOT NULL,
    type        VARCHAR(32),
    description VARCHAR(512),
    operator    VARCHAR(64),
    created_at  TIMESTAMP
);

-- ---------- 审计 ----------
CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    user_id     BIGINT,
    username    VARCHAR(64),
    action      VARCHAR(64),
    target_type VARCHAR(64),
    target_id   VARCHAR(64),
    detail      VARCHAR(1024),
    ip          VARCHAR(64),
    created_at  TIMESTAMP
);

-- =====================================================================
-- 以下为 B 负责模块的数据表（A 定 schema，B 写业务代码）
-- =====================================================================

-- ---------- 时序测量值（按测项存值，对齐基线 §6/§7：value/unit/time/quality/raw_ref） ----------
CREATE TABLE measurement (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    point_id       BIGINT NOT NULL,
    metric_id      BIGINT,
    metric_code    VARCHAR(32),
    device_id      VARCHAR(64),
    message_id     VARCHAR(64) NOT NULL,
    seq            BIGINT,
    schema_version VARCHAR(16),
    measure_value  NUMERIC(18, 6),
    unit           VARCHAR(16),
    quality        VARCHAR(16),
    attributes     VARCHAR(1024),
    raw_ref        VARCHAR(512),
    collect_time   TIMESTAMP,
    receive_time   TIMESTAMP,
    created_at     TIMESTAMP,
    CONSTRAINT uk_measurement_device_msg UNIQUE (device_id, message_id)
);
CREATE INDEX idx_measurement_point_time ON measurement (point_id, collect_time);

-- ---------- 告警规则 / 警情 / 处置 ----------
CREATE TABLE alarm_rule (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    name                    VARCHAR(128) NOT NULL,
    point_id                BIGINT,                       -- NULL=全局规则（作用于所有测点）
    metric_code             VARCHAR(16),                  -- 测项编码，与 metric.code 对齐（D1 冻结后为 defo_mm/rate_mm_d）
    rule_type               VARCHAR(16),                  -- THRESHOLD(累计) / RATE(速率) / CHANGE(变化量)
    operator                VARCHAR(8)  NOT NULL DEFAULT 'gte',  -- gte / lte
    threshold_value         NUMERIC(18, 6),               -- 触发阈值
    window_minutes          INT,                          -- 时间窗口（RATE/CHANGE 判定用）
    recovery_value          NUMERIC(18, 6),               -- 恢复阈值（解除条件）
    alarm_level             VARCHAR(16),                  -- notice / warning / alarm
    repeat_suppress_seconds INT,                          -- 同规则同点防刷屏间隔
    enabled                 BOOLEAN NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP,
    updated_at              TIMESTAMP
);

CREATE TABLE alarm (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    point_id      BIGINT NOT NULL,
    rule_id       BIGINT,
    alarm_level   VARCHAR(16),
    status        VARCHAR(32) NOT NULL,
    trigger_value NUMERIC(18, 6),
    triggered_at  TIMESTAMP,
    resolved_at   TIMESTAMP,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP
);

CREATE TABLE alarm_action (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    alarm_id    BIGINT NOT NULL,
    action_type VARCHAR(32),
    operator    VARCHAR(64),
    note        VARCHAR(1024),
    created_at  TIMESTAMP
);

-- D5 冻结枚举（M0, 2026-09-09，对齐《B侧接口契约_M0》）：
--   alarm_rule.rule_type   : THRESHOLD / RATE / CHANGE
--   alarm_rule.alarm_level : notice / warning / alarm
--   alarm.status           : PENDING / CONFIRMED / PROCESSING / OBSERVING / RESOLVED / FALSE_ALARM
--   alarm_action.action_type: confirm / research / dispatch / handle / resolve / misreport

-- ---------- 媒体（无人机影像） ----------
CREATE TABLE media (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    point_id    BIGINT,
    file_name   VARCHAR(255),
    file_path   VARCHAR(512),
    url         VARCHAR(512),
    uploaded_by VARCHAR(64),
    created_at  TIMESTAMP
);
