-- =====================================================================
-- V24 测量基准版本（复查清单 P1-4）
--
-- 要解决的问题：雷达上报的 defo_mm 是**相对某次基准的累计形变**。换个反射器、把设备
-- 重新装一次、或者设备自己归零之后，这个累计值会从 0 重新开始，而平台这边看到的
-- 只是一条继续延伸的曲线——**两段不同基准的数据被接在了同一条线上**。
-- 那是形变监测里最容易得出错误结论的一类问题：一段"降到 0"的曲线既可以读成
-- 「稳定了」，也可以读成「换了基准」，而只看着曲线的人分不出来。
--
-- 表的设计（四列是这件事的最小充分集）：
--   effective_from  这一版基准从哪一刻起生效。用**时间**而不是"第几条数据"：
--                   数据会补报（BACKFILL）、会乱序到达，序号不可靠，而物理事件发生在时刻上。
--   reason          为什么换基准（白名单短码，见 MeasurementBaselineService）。
--                   自由文本会让"为什么"漂成每人一种写法，查询与统计都做不了。
--   baseline_value_mm 换基准时该点的读数（可空）：将来要"按当前基准折算"时，
--                   折算基准就是这个值；不在同一个基准里比较数值，是这条记录存在的意义。
--   operator        谁登记的（从登录身份取，不采信请求体——与处置留痕同一口径）。
--
-- 为什么不做"设备自动上报基准变更"：契约（docs/message-contract.md）里没有承载基准的字段，
-- 凭空发明一个字段只会让 B 侧无从对接。人工登记 + 审计留痕是当前唯一诚实的选择；
-- 等真实设备接进来、确认它到底怎么表达"归零"，再考虑把它接进入口。
--
-- 为什么 (point_id, effective_from) 加唯一约束：同一时刻只可能有一个基准生效，
-- 重复登记多半是点错了按钮。库级拦住比"后写覆盖先写"安全——覆盖会静默丢掉一条留痕。
-- =====================================================================

CREATE TABLE measurement_baseline (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    point_id          BIGINT NOT NULL,
    effective_from    TIMESTAMP NOT NULL,
    reason            VARCHAR(32) NOT NULL,
    note              VARCHAR(512),
    baseline_value_mm NUMERIC(18, 6),
    operator          VARCHAR(64),
    created_at        TIMESTAMP,
    CONSTRAINT uk_baseline_point_time UNIQUE (point_id, effective_from)
);

-- 取"当前基准"与"窗口内的基准"都走 (point_id, effective_from)：
-- 前者是 <= now 里最大的一条，后者是区间扫描，同一个索引全覆盖。
CREATE INDEX idx_baseline_point_time ON measurement_baseline (point_id, effective_from);
