-- =====================================================================
-- V8 项目数据范围隔离（验收第 7 条前半）
--
-- 需求原话是「项目数据范围隔离」。此前 sys_user 上只有 organization_id，
-- 而种子是 1 组织 1 项目——组织级隔离在这个种子上**演示不出来**（谁来都看到同一份）。
-- 所以建显式的项目成员表：可见范围 = 你被加进了哪些项目。
--
-- 为什么不复用 organization_id：一个组织可以下有多个项目，两者不是同一个粒度；
-- 要演示的两种情形（同组织内也隔离 / 跨组织不可见）一列 organization_id 表达不了。
--
-- 成员关系用**硬删除**（无 deleted 列），与 device_point 一致：唯一约束
-- (user_id, project_id) 与软删除天然冲突——软删后再加回来会撞唯一键，
-- 而「移除成员」本来就该是幂等的增删。
--
-- 种子刻意拆成两处，理由与「账号本身不进 Flyway」是同一个：
--   本迁移          —— 组织 2 / 项目 2 及其场景-对象-测点（静态数据，id 可显式指定）
--   ProjectMemberInitializer（运行时）—— 成员关系。sys_user.id 是启动时由 DataInitializer
--   创建的，而 Flyway 跑在 CommandLineRunner **之前**，那一刻 sys_user 还是空表，
--   在这里写 user_id 只能是悬空外键（或硬编码 1~4 而这些 id 在新库上还不存在）。
--
-- 项目 2 有 2 个测点而不是空壳：否则「李敏看不到项目 B 的测点」只是「看不见一个空列表」，
-- 断言与演示都是空的。代价是 /points 的种子期望从 7 变成 9（01 套件同步改）。
-- =====================================================================

CREATE TABLE project_member (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT uk_project_member UNIQUE (user_id, project_id)
);

-- 查询一律是「按当前用户查可见项目」，故按 user_id 建索引
CREATE INDEX idx_project_member_user ON project_member (user_id);

-- ---------- 第二个组织与项目（另一客户，用来演示隔离） ----------
INSERT INTO organization (id, name, code, contact, phone, created_at, updated_at)
VALUES (2, '西江水泥', 'ORG-XJ', '周工', '0766-0000000', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO project (id, organization_id, name, code, location, description, created_at, updated_at)
VALUES (2, 2, '西江水泥采空区形变监测', 'PRJ-XJ-CKQ', '广东省云浮市',
        '毫米波点形变雷达监测采空区地表沉降', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO scene (id, project_id, name, type, description, created_at, updated_at) VALUES
(3, 2, '采空区', 'GOAF', '采空区地表监测（2 个测点）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO monitor_object (id, scene_id, name, type, description, created_at, updated_at) VALUES
(3, 3, '采空区地表', 'GOAF_SURFACE', '采空区上方地表', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO monitor_point (id, object_id, code, name, type, longitude, latitude, altitude, enabled, created_at, updated_at) VALUES
(8, 3, 'P-CKQ01', '采空区测点1', 'POINT_DEFORMATION', 112.0400000, 22.9300000, 80.000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 3, 'P-CKQ02', '采空区测点2', 'POINT_DEFORMATION', 112.0412000, 22.9306000, 84.000, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 测项：口径同 V2（每点 defo_mm + rate_mm_d，无 X/Y/Z 三分量）
INSERT INTO metric (id, point_id, code, name, unit, sort_order, created_at, updated_at) VALUES
(15, 8, 'defo_mm',   '累计形变', 'mm',   1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 8, 'rate_mm_d', '形变速率', 'mm/d', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 9, 'defo_mm',   '累计形变', 'mm',   1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 9, 'rate_mm_d', '形变速率', 'mm/d', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
